### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by beeso018** [jackstanek/BotBot#24]
Running in my home directory, I get this NameError:

(BotBot) beesons@login02 [~] % botbot file ./
Traceback (most recent call last):
  File "/home/mccuem/beesons/.botbot/conda/envs/BotBot/bin/botbot", line 9, in <module>
    load_entry_point('BotBot', 'console_scripts', 'botbot')()
  File "/panfs/roc/groups/3/mccuem/beesons/.local/bin/BotBot/botbot/botbot.py", line 97, in main
    me=args.me,
  File "/panfs/roc/groups/3/mccuem/beesons/.local/bin/BotBot/botbot/checker.py", line 216, in check_all
    self.reporter.write_report(fmt, shared)
  File "/panfs/roc/groups/3/mccuem/beesons/.local/bin/BotBot/botbot/report.py", line 76, in write_report
    if should_print_report(filelist):
NameError: name 'should_print_report' is not defined

**Comment by jackstanek** [comment]
Should be fixed now
